services:
  sql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_pravin8470_PASSWORD: "Puja@8470"
    platform: "linux/amd64"
    ports:
     - "1433:1433"  